


enum { RESET_BYTE = 0, SET_BYTE, RESET_BIT,SET_BIT,READ_BYTE, READ_BIT,ANALOG_READ,ANSWER ,SET_TIME,GET_TIME,SET_CHRONO,SET_PROGRAMME,RESET_EEPROM ,SET_ID, SET_TEMP_OFFSET, GET_TEMP, TIME_CALIBRATION };
enum { COMMAND=0,VALUE, VALUE1, VALUE2 };
enum { INDEX=0, HIGH_TIME=0 , LOW_TIME ,ZERO_BYTE , ONE_BYTE };


#define TIME_AFTER_SEND	1
#define TIME_BEFORE_SEND	500

#define DEBUG_NET

#ifndef DEBUG_SERIAL
#define DEBUG_PORT Debug
#else
#define DEBUG_PORT Serial
#endif
